# Generated by Django 5.1.5 on 2025-09-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('paypal', 'PayPal'), ('bank_transfer', 'Transferencia Bancaria'), ('cash_on_delivery', 'Pago Contra Entrega'), ('mercadopago', 'MercadoPago')], max_length=20),
        ),
    ]
